'use strict';
const $=s=>document.querySelector(s);
const els={messages:$('#messages'),form:$('#chatForm'),input:$('#messageInput'),send:$('#sendBtn'),newChat:$('#newChatBtn'),settings:$('#settingsBtn'),dialog:$('#settingsDialog'),apiUrl:$('#apiUrl'),userId:$('#userId'),save:$('#saveSettings'),error:$('#errorBanner'),errorText:$('#errorText'),closeError:$('#closeError')};
const state={apiUrl:localStorage.getItem('vp_api_url')||'http://127.0.0.1:8000/api/v1/chat',userId:localStorage.getItem('vp_user_id')||'web-demo-user',sessionId:newSession(),sending:false};
els.apiUrl.value=state.apiUrl;els.userId.value=state.userId;
function newSession(){return 'web-'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2));}
function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML;}
function fmt(v){return esc(v).replace(/\n{2,}/g,'</p><p>').replace(/\n/g,'<br>');}
function time(){return new Intl.DateTimeFormat('vi-VN',{hour:'2-digit',minute:'2-digit'}).format(new Date());}
function scroll(){els.messages.scrollTop=els.messages.scrollHeight;}
function showError(m){els.errorText.textContent=m;els.error.hidden=false;}function hideError(){els.error.hidden=true;els.errorText.textContent='';}
function addUser(text){const n=document.createElement('div');n.className='message user';n.innerHTML=`<div class="bubble-wrap"><div class="bubble">${fmt(text)}</div><small>${time()}</small></div>`;els.messages.appendChild(n);scroll();}
function typing(){const n=document.createElement('div');n.className='message assistant';n.innerHTML='<div class="avatar small">V</div><div class="bubble-wrap"><div class="bubble typing"><i></i><i></i><i></i></div></div>';els.messages.appendChild(n);scroll();return n;}
function sourcesHtml(sources){if(!Array.isArray(sources)||!sources.length)return'';return `<details class="sources"><summary>Xem ${sources.length} nguồn dữ liệu</summary>${sources.slice(0,6).map(s=>`<div class="source"><strong>${esc(s.source_file||'Unknown')}</strong>${esc(s.category||'unknown')}${s.path?' · '+esc(s.path):''}${typeof s.score==='number'?' · '+Math.round(s.score*100)+'%':''}</div>`).join('')}</details>`;}
function addAssistant(p){const n=document.createElement('div');n.className='message assistant';n.innerHTML=`<div class="avatar small">V</div><div class="bubble-wrap"><div class="bubble"><p>${fmt(p.answer||'Không có nội dung phản hồi.')}</p>${p.ticket_id?`<div class="ticket"><strong>Ticket:</strong> ${esc(p.ticket_id)}</div>`:''}${sourcesHtml(p.sources)}<div class="meta"><span>${esc(p.route||'unknown')}</span><span>${esc(p.language||'unknown')}</span></div></div><small>${time()}</small></div>`;els.messages.appendChild(n);scroll();}
function setSending(v){state.sending=v;els.send.disabled=v;els.input.disabled=v;}
async function callApi(message){const c=new AbortController(),t=setTimeout(()=>c.abort(),90000);try{const r=await fetch(state.apiUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,session_id:state.sessionId,user_id:state.userId}),signal:c.signal});let b=null;try{b=await r.json();}catch{}if(!r.ok)throw new Error(b?.detail||`FastAPI trả về HTTP ${r.status}`);return b;}catch(e){if(e.name==='AbortError')throw new Error('Yêu cầu quá thời gian chờ. Gemini hoặc FastAPI có thể đang bận.');if(e instanceof TypeError)throw new Error('Không thể kết nối FastAPI. Hãy kiểm tra server, API URL và CORS.');throw e;}finally{clearTimeout(t);}}
async function send(raw){const message=raw.trim();if(!message||state.sending)return;hideError();setSending(true);addUser(message);$('#suggestions')?.remove();els.input.value='';els.input.style.height='auto';const wait=typing();try{const p=await callApi(message);wait.remove();addAssistant(p);}catch(e){wait.remove();showError(e.message||'Đã xảy ra lỗi.');addAssistant({answer:'Xin lỗi, hệ thống đang tạm thời không thể xử lý yêu cầu. Vui lòng thử lại sau.',language:'vi',route:'system_error',sources:[]});}finally{setSending(false);els.input.focus();}}
els.form.addEventListener('submit',e=>{e.preventDefault();send(els.input.value);});
els.input.addEventListener('input',()=>{els.input.style.height='auto';els.input.style.height=Math.min(els.input.scrollHeight,140)+'px';});
els.input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();els.form.requestSubmit();}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-question]');if(b)send(b.dataset.question||'');});
els.newChat.addEventListener('click',()=>{state.sessionId=newSession();hideError();els.messages.innerHTML='<div class="message assistant"><div class="avatar small">V</div><div class="bubble-wrap"><div class="bubble">Cuộc trò chuyện mới đã bắt đầu. Bạn muốn khám phá điểm đến hoặc trải nghiệm nào của Vinpearl?</div><small>Vừa xong</small></div></div>';els.input.focus();});
els.settings.addEventListener('click',()=>els.dialog.showModal());
els.save.addEventListener('click',e=>{e.preventDefault();const u=els.apiUrl.value.trim();if(!u){showError('API URL không được để trống.');return;}state.apiUrl=u;state.userId=els.userId.value.trim()||'web-demo-user';localStorage.setItem('vp_api_url',state.apiUrl);localStorage.setItem('vp_user_id',state.userId);els.dialog.close();hideError();});
els.closeError.addEventListener('click',hideError);
els.dialog.addEventListener('click',e=>{if(e.target===els.dialog)els.dialog.close();});
