"""split content tables back into four owner-specific tables

Undoes the polymorphic content_section / content_block introduced in
9b9c2a68204e. 41 tables -> 43.

Why revert: a polymorphic table trades two real foreign keys for one fewer
table, and that trade only pays when there are many owner types. media has 8
owners, so it earns it. content_* had exactly 2, so it did not - and the cost
was concrete: no FK, no ON DELETE CASCADE, and DataGrip cannot draw the
relationship at all, leaving the table floating with no visible owner.

Row data is not copied. Primary keys are deterministic hashes seeded with the
table name, so carried-over rows would keep dead ids. Rebuild instead:

    python -m alembic upgrade head
    python -m scripts.load_core

One thing kept from the merge: promotion_block.block_type says 'list' where it
used to say 'bullet_list', matching policy_block. Same payload shape, so the two
tables now read identically even though they stay separate.

Revision ID: 5da78849e068
Revises: e94fc771da30
Create Date: 2026-08-09 23:22:24.024200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5da78849e068'
down_revision: Union[str, Sequence[str], None] = 'e94fc771da30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


POLICY_VIEW_BODY = """
SELECT
    pd.id,
    pd.title,
    pd.category,
    pd.word_count,
    pd.effective_from,
    (SELECT jsonb_agg(jsonb_build_object(
                'heading', ps.heading,
                'content', ps.content)
              ORDER BY ps.ord)
       FROM core.policy_section ps WHERE ps.document_id = pd.id)          AS sections,
    (SELECT count(*)
       FROM core.policy_block pb WHERE pb.document_id = pd.id)            AS block_count,
    pd.plain_text
FROM core.policy_document pd
WHERE pd.is_active
"""

# Bản cũ của view này đọc core.content_section. Postgres không cho DROP một bảng
# còn view phụ thuộc, nên phải gỡ view trước rồi dựng lại trên bảng mới.
OLD_POLICY_VIEW_BODY = """
SELECT
    pd.id, pd.title, pd.category, pd.word_count, pd.effective_from,
    (SELECT jsonb_agg(jsonb_build_object('heading', cs.heading, 'content', cs.content)
              ORDER BY cs.ord)
       FROM core.content_section cs
      WHERE cs.entity_type = 'policy_document' AND cs.entity_id = pd.id)  AS sections,
    (SELECT count(*) FROM core.content_block cb
      WHERE cb.entity_type = 'policy_document' AND cb.entity_id = pd.id)  AS block_count,
    pd.plain_text
FROM core.policy_document pd
WHERE pd.is_active
"""


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP VIEW IF EXISTS api.policy_document")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_block',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("block_type IN ('table','list')", name=op.f('ck_policy_block_block_type_valid')),
    sa.ForeignKeyConstraint(['document_id'], ['core.policy_document.id'], name=op.f('fk_policy_block_document_id_policy_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_block')),
    sa.UniqueConstraint('document_id', 'ord', name='uq_policy_block_ord'),
    schema='core'
    )
    op.create_table('policy_section',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['core.policy_document.id'], name=op.f('fk_policy_section_document_id_policy_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_section')),
    sa.UniqueConstraint('document_id', 'ord', name='uq_policy_section_ord'),
    schema='core'
    )
    op.create_table('promotion_block',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("block_type IN ('table','list','heading')", name=op.f('ck_promotion_block_block_type_valid')),
    sa.ForeignKeyConstraint(['promotion_id'], ['core.promotion.id'], name=op.f('fk_promotion_block_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_block')),
    sa.UniqueConstraint('promotion_id', 'ord', name='uq_promotion_block_ord'),
    schema='core'
    )
    op.create_table('promotion_section',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('promotion_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['core.promotion.id'], name=op.f('fk_promotion_section_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_section')),
    sa.UniqueConstraint('promotion_id', 'ord', name='uq_promotion_section_ord'),
    schema='core'
    )
    op.drop_index(op.f('ix_content_section_entity'), table_name='content_section', schema='core')
    op.drop_table('content_section', schema='core')
    op.drop_index(op.f('ix_content_block_entity'), table_name='content_block', schema='core')
    op.drop_table('content_block', schema='core')
    # ### end Alembic commands ###
    op.execute(f"CREATE VIEW api.policy_document AS{POLICY_VIEW_BODY}")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS api.policy_document")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_block',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ord', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('block_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("block_type = ANY (ARRAY['table'::text, 'list'::text, 'heading'::text])", name=op.f('ck_content_block_block_type_valid')),
    sa.CheckConstraint("entity_type = ANY (ARRAY['promotion'::text, 'policy_document'::text])", name=op.f('ck_content_block_entity_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_block')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'ord', name=op.f('uq_content_block_ord'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='core'
    )
    op.create_index(op.f('ix_content_block_entity'), 'content_block', ['entity_type', 'entity_id'], unique=False, schema='core')
    op.create_table('content_section',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ord', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('heading', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("entity_type = ANY (ARRAY['promotion'::text, 'policy_document'::text])", name=op.f('ck_content_section_entity_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_section')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'ord', name=op.f('uq_content_section_ord'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='core'
    )
    op.create_index(op.f('ix_content_section_entity'), 'content_section', ['entity_type', 'entity_id'], unique=False, schema='core')
    op.drop_table('promotion_section', schema='core')
    op.drop_table('promotion_block', schema='core')
    op.drop_table('policy_section', schema='core')
    op.drop_table('policy_block', schema='core')
    # ### end Alembic commands ###
    op.execute(f"CREATE VIEW api.policy_document AS{OLD_POLICY_VIEW_BODY}")
