"""merge 4 link tables into columns and polymorphic content

45 tables -> 41:
  room_amenity      -> room.amenity_ids TEXT[]
  promotion_tag     -> promotion.tags JSONB
  promotion_section + policy_section -> content_section (polymorphic)
  promotion_block   + policy_block   -> content_block   (polymorphic)

This migration does NOT copy row data across. Primary keys are deterministic
hashes seeded with the table name, so rows carried over would keep dead ids and
the next load would insert a second copy alongside them. The JSON files under
data/ are the source of truth, so the rebuild is the safe path:

    python -m alembic upgrade head
    python -m scripts.load_core

Until that load runs, room.amenity_ids and promotion.tags are NULL and both
content_* tables are empty.

Revision ID: 9b9c2a68204e
Revises: b4f6feb94662
Create Date: 2026-08-09 21:54:57.847633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9c2a68204e'
down_revision: Union[str, Sequence[str], None] = 'b4f6feb94662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_block',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("block_type IN ('table','list','heading')", name=op.f('ck_content_block_block_type_valid')),
    sa.CheckConstraint("entity_type IN ('promotion','policy_document')", name=op.f('ck_content_block_entity_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_block')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'ord', name='uq_content_block_ord')
    )
    op.create_index('ix_content_block_entity', 'content_block', ['entity_type', 'entity_id'], unique=False)
    op.create_table('content_section',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('promotion','policy_document')", name=op.f('ck_content_section_entity_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_section')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'ord', name='uq_content_section_ord')
    )
    op.create_index('ix_content_section_entity', 'content_section', ['entity_type', 'entity_id'], unique=False)
    op.drop_table('promotion_block')
    op.drop_table('room_amenity')
    op.drop_table('promotion_section')
    op.drop_table('policy_section')
    op.drop_index(op.f('ix_promotion_tag_type_value'), table_name='promotion_tag')
    op.drop_table('promotion_tag')
    op.drop_table('policy_block')
    op.add_column('promotion', sa.Column('tags', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.create_index('ix_promotion_tags', 'promotion', ['tags'], unique=False, postgresql_using='gin')
    op.add_column('room', sa.Column('amenity_ids', postgresql.ARRAY(sa.Text()), nullable=True))
    op.create_index('ix_room_amenity_ids', 'room', ['amenity_ids'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_amenity_ids', table_name='room', postgresql_using='gin')
    op.drop_column('room', 'amenity_ids')
    op.drop_index('ix_promotion_tags', table_name='promotion', postgresql_using='gin')
    op.drop_column('promotion', 'tags')
    op.create_table('policy_block',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ord', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('block_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("block_type = ANY (ARRAY['table'::text, 'list'::text])", name=op.f('ck_policy_block_block_type_valid')),
    sa.ForeignKeyConstraint(['document_id'], ['policy_document.id'], name=op.f('fk_policy_block_document_id_policy_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_block'))
    )
    op.create_table('promotion_tag',
    sa.Column('promotion_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tag_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tag_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.CheckConstraint("tag_type = ANY (ARRAY['promotion_type'::text, 'service'::text, 'channel'::text, 'customer_group'::text, 'member_tier'::text])", name=op.f('ck_promotion_tag_tag_type_valid')),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_tag_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('promotion_id', 'tag_type', 'tag_value', name=op.f('pk_promotion_tag'))
    )
    op.create_index(op.f('ix_promotion_tag_type_value'), 'promotion_tag', ['tag_type', 'tag_value'], unique=False)
    op.create_table('policy_section',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ord', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('heading', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['policy_document.id'], name=op.f('fk_policy_section_document_id_policy_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_section')),
    sa.UniqueConstraint('document_id', 'ord', name=op.f('uq_policy_section_ord'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('promotion_section',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('promotion_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ord', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('heading', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_section_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_section')),
    sa.UniqueConstraint('promotion_id', 'ord', name=op.f('uq_promotion_section_ord'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('room_amenity',
    sa.Column('room_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('amenity_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], name=op.f('fk_room_amenity_amenity_id_amenity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_room_amenity_room_id_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'amenity_id', name=op.f('pk_room_amenity'))
    )
    op.create_table('promotion_block',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('promotion_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ord', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('block_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("block_type = ANY (ARRAY['table'::text, 'bullet_list'::text, 'heading'::text])", name=op.f('ck_promotion_block_block_type_valid')),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_block_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_block'))
    )
    op.drop_index('ix_content_section_entity', table_name='content_section')
    op.drop_table('content_section')
    op.drop_index('ix_content_block_entity', table_name='content_block')
    op.drop_table('content_block')
    # ### end Alembic commands ###
