"""merge 3 tables: step into term, map into feature, itinerary into jsonb

Revision ID: b4f6feb94662
Revises: e1a3d9b2b327
Create Date: 2026-08-09 17:48:18.316132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4f6feb94662'
down_revision: Union[str, Sequence[str], None] = 'e1a3d9b2b327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('golf_course_map')
    op.drop_table('attraction_itinerary_day')
    op.drop_table('promotion_step')
    op.add_column('attraction', sa.Column('itinerary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('golf_feature', sa.Column('variant', sa.Text(), nullable=True))
    # promotion_term doi cong thuc khoa chinh: stable_id(pid, ord) -> (pid, kind, ord),
    # va 'ord' chuyen tu dem chung sang dem rieng theo tung kind. Dong cu vi the
    # khong duoc upsert de len ma nam lai, gay trung (promotion_id, kind, ord).
    # Xoa sach roi nap lai bang scripts.load_core — moi dong deu sinh lai duoc.
    op.execute("DELETE FROM promotion_term")
    op.create_unique_constraint('uq_promotion_term_ord', 'promotion_term', ['promotion_id', 'kind', 'ord'])

    # Autogenerate KHONG phat hien thay doi cua CHECK constraint. Thieu phan nay
    # thi kind='map' va kind='step' bi tu choi voi SQLSTATE 23514.
    #
    # Dung SQL thang thay vi op.drop_constraint: quy uoc dat ten trong base.py
    # (ck_%(table_name)s_%(constraint_name)s) se them tien to lan thu hai vao ten
    # da day du, thanh 'ck_golf_feature_ck_golf_feature_kind_valid'.
    op.execute("ALTER TABLE golf_feature DROP CONSTRAINT ck_golf_feature_kind_valid")
    op.execute(
        "ALTER TABLE golf_feature ADD CONSTRAINT ck_golf_feature_kind_valid "
        "CHECK (kind IN ('feature','award','amenity','experience','map'))"
    )
    op.execute("ALTER TABLE promotion_term DROP CONSTRAINT ck_promotion_term_kind_valid")
    op.execute(
        "ALTER TABLE promotion_term ADD CONSTRAINT ck_promotion_term_kind_valid "
        "CHECK (kind IN ('term','combination','contact','step'))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rows carrying the kinds this migration introduced have to go before the
    # narrower CHECK comes back, otherwise ALTER TABLE fails with
    # "check constraint ... is violated by some row" and the whole downgrade
    # chain stops here. Deleting is safe: upgrade() did not copy these rows in
    # from anywhere, load_core rebuilds them from data/*.json.
    op.execute("DELETE FROM promotion_term WHERE kind = 'step'")
    op.execute("DELETE FROM golf_feature WHERE kind = 'map'")

    op.execute("ALTER TABLE promotion_term DROP CONSTRAINT ck_promotion_term_kind_valid")
    op.execute(
        "ALTER TABLE promotion_term ADD CONSTRAINT ck_promotion_term_kind_valid "
        "CHECK (kind IN ('term','combination','contact'))"
    )
    op.execute("ALTER TABLE golf_feature DROP CONSTRAINT ck_golf_feature_kind_valid")
    op.execute(
        "ALTER TABLE golf_feature ADD CONSTRAINT ck_golf_feature_kind_valid "
        "CHECK (kind IN ('feature','award','amenity','experience'))"
    )
    op.drop_constraint('uq_promotion_term_ord', 'promotion_term', type_='unique')
    op.drop_column('golf_feature', 'variant')
    op.drop_column('attraction', 'itinerary')
    op.create_table('promotion_step',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('promotion_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ord', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotion.id'], name=op.f('fk_promotion_step_promotion_id_promotion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_step')),
    sa.UniqueConstraint('promotion_id', 'ord', name=op.f('uq_promotion_step_ord'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('attraction_itinerary_day',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attraction_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('heading', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attraction_id'], ['attraction.id'], name=op.f('fk_attraction_itinerary_day_attraction_id_attraction'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attraction_itinerary_day')),
    sa.UniqueConstraint('attraction_id', 'day_number', name=op.f('uq_itinerary_day'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('golf_course_map',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('course_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('map_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('map_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingest_run_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['golf_course.id'], name=op.f('fk_golf_course_map_course_id_golf_course'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], name=op.f('fk_golf_course_map_ingest_run_id_ingest_run'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_golf_course_map_source_id_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_golf_course_map'))
    )
    # ### end Alembic commands ###
